site_name: Linguini
site_url: https://cs3216-a3-g7.github.io/linguini/
repo_url: https://github.com/CS3216-A3-G7/linguini

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - tables
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Architecture: architecture.md
  - Local development: local-development.md
  - Testing: testing.md
  - Database: database.md
  - ERD: erd.md
